subastas_repo/personas/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url

from personas import views

urlpatterns = patterns('',
    url(
        regex=r'^asociar/(?P<subasta_id>\d+)$',
        view=views.asociar,
        name='asociar'
    ),
    url(
        regex=r'^desasociar/(?P<subasta_id>\d+)/(?P<persona_id>\d+)$',
        view=views.desasociar,
        name='desasociar'
    ),
    url(
        regex=r'^profesionales/$',
        view=views.ProfesionalListView.as_view(),
        name='profesionales_list'
    ),
    url(
        regex=r'^profesionales/create/$',
        view=views.ProfesionalCreateView.as_view(),
        name='profesionales_create'
    ),
    url(
        regex=r'^profesionales/update/(?P<pk>\d+)/$',
        view=views.ProfesionalUpdateView.as_view(),
        name='profesionales_update'
    ),
    url(
        regex=r'^profesionales/delete/(?P<pk>\d+)/$',
        view=views.ProfesionalDeleteView.as_view(),
        name='profesionales_delete'
    ),
)

subastas_repo/subastas/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

from . import views

urlpatterns = patterns('subastas.views',
    url(
        regex=r'^$',
        view=views.SubastaListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^nuevo/$',
        view=views.SubastaCreateView.as_view(),
        name='create'
    ),
    url(
        regex=r'^editar/(?P<pk>\d+)/$',
        view=views.SubastaUpdateView.as_view(),
        name='update'
    ),
    url(
        regex=r'^cerrar/(?P<subasta_id>\d+)/$',
        view=views.cerrar_subasta,
        name='close'
    ),
    url(
        regex=r'^actas/$',
        view=views.ActaListView.as_view(),
        name='actas'
    ),
    url(
        regex=r'^actas/nuevo/$',
        view=views.ActaCreateView.as_view(),
        name='actas_create'
    ),
    url(
        regex=r'^imprimir/(?P<pk>\d+)/$',
        view=views.ActaPrintView.as_view(),
        name='print'
    ),
    url(
        regex=r'^acreditadores/$',
        view=views.AcreditadorHomeView.as_view(),
        name='acreditadores'
    ),
    url(
        regex=r'^bienes/$',
        view=views.RodadoListView.as_view(),
        name='rodados'
    ),
    url(
        regex=r'^bienes/nuevo/$',
        view=views.RodadoCreateView.as_view(),
        name='rodados_create'
    ),
    url(
        regex=r'^bienes/editar/(?P<pk>\d+)/$',
        view=views.RodadoUpdateView.as_view(),
        name='rodados_update'
    ),
    url(
        regex=r'^bienes/nuevo/xlsx/$',
        view=views.upload_xlsx,
        name='rodados_nuevo_xlsx'
    ),
    url(
        regex=r'^grupos/$',
        view=views.GrupoListView.as_view(),
        name='grupos'
    ),
    url(
        regex=r'^grupos/(?P<pk>\d+)$',
        view=views.GrupoDetailView.as_view(),
        name='grupos_detail'
    ),
    url(
        regex=r'^grupos/nuevo/$',
        view=views.GrupoCreateView.as_view(),
        name='grupos_create'
    ),
    url(
        regex=r'^grupos/editar/(?P<pk>\d+)/$',
        view=views.GrupoUpdateView.as_view(),
        name='grupos_update',
    ),
    url(
        regex=r'^lotes/$',
        view=views.LoteListView.as_view(),
        name='lotes'
    ),
    url(
        regex=r'^lotes/(?P<pk>\d+)/$',
        view=views.LoteDetailView.as_view(),
        name='lotes_detail'
    ),
    url(
        regex=r'^lotes/nuevo/$',
        view=views.LoteCreateView.as_view(),
        name='lotes_create'
    ),
    url(
        regex=r'^lotes/editar/(?P<pk>\d+)/$',
        view=views.LoteUpdateView.as_view(),
        name='lotes_update'
    ),
    # Sin permisos
    url(
        regex=r'^sin_permisos/$',
        view=TemplateView.as_view(
            template_name='subastas/sin_permisos.html'),
        name='sin_permisos'
    ),
)

subastas_repo/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$',  'subastas.views.home', name="home"),

    (r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),

    # User management
    url(r'^users/', include("users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    # Uncomment the next line to enable avatars
    url(r'^avatar/', include('avatar.urls')),

    # Your stuff: custom urls go here
    url(r'^subastas/', include("subastas.urls", namespace="subastas")),
    url(r'^personas/', include("personas.urls", namespace="personas")),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

subastas_repo/subastas/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse, reverse_lazy
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.views.generic import CreateView
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic import UpdateView
from django.views.generic import FormView

from braces.views import LoginRequiredMixin

from personas.forms import PersonaForm
from personas.models import Persona
from .forms import (ActaForm,
                    GrupoForm,
                    InscriptionForm,
                    LoteForm,
                    RodadoForm,
                    SubastaForm)
from .models import (Acta,
                     Grupo,
                     Lote,
                     Rodado,
                     Subasta)


@login_required
def home(request):
    if request.user.groups.filter(name="administradores").exists():
        url = 'subastas:list'
    elif request.user.groups.filter(name="acreditadores").exists():
        url = 'subastas:acreditadores'
    elif request.user.groups.filter(name="acteros").exists():
        url = 'subastas:actas'
    else:
        url = 'subastas:sin_permisos'

    return redirect(reverse(url))


class SubastaListView(LoginRequiredMixin, ListView):
    model = Subasta
    template_name = 'subastas/list.html'

    def get_queryset(self):
        """Subastas anteriores o cerradas"""
        return Subasta.objects.filter(Q(cerrado_el__lte=timezone.now()) |
                                      Q(fecha_hora__lte=timezone.now()))


class SubastaCreateView(LoginRequiredMixin, CreateView):
    form_class = SubastaForm
    model = Subasta
    success_url = reverse_lazy('subastas:list')
    template_name = 'subastas/form.html'

    def form_valid(self, form):
        form.save()
        messages.add_message(self.request,
                             messages.INFO,
                             'Subasta creada exitosamente.')
        return super(SubastaCreateView, self).form_valid(form)


class SubastaUpdateView(LoginRequiredMixin, UpdateView):
    context_object_name = 'instance'
    form_class = SubastaForm
    model = Subasta
    success_url = reverse_lazy('subastas:list')
    template_name = 'subastas/form.html'

    def form_valid(self, form):
        messages.add_message(self.request,
                             messages.INFO,
                             'Subasta modificada exitosamente.')
        return super(SubastaUpdateView, self).form_valid(form)


def cerrar_subasta(request, subasta_id):
    subasta = get_object_or_404(Subasta, pk=subasta_id)
    subasta.cerrado_el = timezone.now()
    subasta.save()
    messages.add_message(request,
                         messages.INFO,
                         'Subasta cerrada exitosamente.')
    return redirect(reverse_lazy("subastas:list"))


class ActaListView(LoginRequiredMixin, ListView):
    model = Acta
    template_name = 'subastas/actas/list.html'

    def get_queryset(self):
        self.current_subasta = Subasta.objects.get_current()
        if self.current_subasta:
            return self.current_subasta.actas.all()
        else:
            return None


class ActaCreateView(LoginRequiredMixin, CreateView):
    form_class = ActaForm
    model = Acta
    template_name = 'subastas/actas/form.html'
    success_url = reverse_lazy('subastas:actas')

    def form_valid(self, form):
        acta_nueva = form.save(commit=False)
        acta_nueva.subasta = Subasta.objects.get_current()
        acta_nueva.save()
        messages.add_message(self.request,
                             messages.INFO,
                             'Acta agregada exitosamente.')
        return super(ActaCreateView, self).form_valid(form)


class ActaPrintView(LoginRequiredMixin, DetailView):
    model = Acta
    template_name = 'subastas/actas/print.html'

    def get_context_data(self, **kwargs):
        context = super(ActaPrintView, self).get_context_data(**kwargs)
        acta = kwargs.get('object')
        context['bienes'] = Rodado.objects.filter(lote=acta.lote)
        return context


class AcreditadorHomeView(LoginRequiredMixin, FormView):
    form_class = PersonaForm
    model = Persona
    success_url = reverse_lazy('subastas:acreditadores')
    template_name = 'subastas/acreditador_home.html'

    def get_context_data(self, **kwargs):
        self.current_subasta = Subasta.objects.get_current()
        context = super(AcreditadorHomeView, self).get_context_data(**kwargs)
        if self.current_subasta:
            context['personas'] = self.current_subasta.personas.all() \
                .order_by('apellidos')

            query = self.request.GET.get('q', '')
            context['form_inscriptions'] = InscriptionForm(
                instance=self.current_subasta, query=query)

            context['tab'] = self.request.GET.get('tab', 'search')
            context['query'] = query
        return context

    def form_valid(self, form):
        self.current_subasta = Subasta.objects.get_current()
        persona_acreditada = form.save()
        self.current_subasta.personas.add(persona_acreditada)
        messages.add_message(self.request,
                             messages.INFO,
                             'Inscripcion exitosa.')
        return redirect(reverse_lazy("subastas:acreditadores"))

    def form_invalid(self, form):
        return super(AcreditadorHomeView, self).form_invalid(form)


class RodadoListView(LoginRequiredMixin, ListView):
    model = Rodado
    template_name = 'subastas/rodados/list.html'

    def get_queryset(self):
        """Bienes sin subastar"""
        return Rodado.objects.no_subastados()


class RodadoCreateView(LoginRequiredMixin, CreateView):
    form_class = RodadoForm
    model = Rodado
    template_name = 'subastas/rodados/form.html'
    success_url = reverse_lazy('subastas:rodados')

    def form_valid(self, form):
        messages.add_message(self.request,
                             messages.INFO,
                             'Bien cargado exitosamente.')
        return super(RodadoCreateView, self).form_valid(form)


class RodadoUpdateView(LoginRequiredMixin, UpdateView):
    context_object_name = 'instance'
    form_class = RodadoForm
    model = Rodado
    success_url = reverse_lazy('subastas:rodados')
    template_name = 'subastas/rodados/form.html'

    def form_valid(self, form):
        messages.add_message(self.request,
                             messages.INFO,
                             'Bien modificado exitosamente.')
        return super(RodadoUpdateView, self).form_valid(form)


def upload_xlsx(request):
    if request.method == "POST":
        rodados_cargados = Rodado.objects \
            .load_bienes(request.FILES['bienes_file'])
        messages.add_message(request,
                             messages.INFO,
                             'Bienes cargados: %s' % (rodados_cargados))
    return render(request, 'subastas/rodados/cargar_xlsx.html')


class GrupoListView(LoginRequiredMixin, ListView):
    model = Grupo
    template_name = 'subastas/grupos/list.html'

    def get_queryset(self):
        """Grupos de la subasta vigente"""
        subasta = Subasta.objects.get_current()
        return subasta.grupos.all()


class GrupoDetailView(LoginRequiredMixin, DetailView):
    model = Grupo
    template_name = 'subastas/grupos/detail.html'


class GrupoCreateView(LoginRequiredMixin, CreateView):
    form_class = GrupoForm
    model = Grupo
    template_name = 'subastas/grupos/form.html'
    success_url = reverse_lazy('subastas:grupos')

    def form_valid(self, form):
        grupo = form.save(commit=False)
        grupo.subasta = Subasta.objects.get_current()
        grupo.save()

        lotes = form.cleaned_data.get('lotes', None)
        if lotes:
            lotes.update(grupo=grupo)
        messages.add_message(self.request,
                             messages.INFO,
                             'Grupo cargado exitosamente.')
        return super(GrupoCreateView, self).form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(GrupoCreateView, self).get_form_kwargs()

        # solo los lotes que no tienen grupo y su subasta no esta cerrada
        lotes = Lote.objects.filter(grupo__subasta__cerrado_el=None,
                                    grupo=None)
        kwargs['lotes'] = lotes
        return kwargs


class GrupoUpdateView(LoginRequiredMixin, UpdateView):
    context_object_name = 'instance'
    form_class = GrupoForm
    model = Grupo
    success_url = reverse_lazy('subastas:grupos')
    template_name = 'subastas/grupos/form.html'

    def form_valid(self, form):
        grupo = form.save(commit=False)
        grupo.lotes.update(grupo=None)

        lotes = form.cleaned_data.get('lotes', None)
        if lotes:
            lotes.update(grupo=grupo)

        messages.add_message(self.request,
                             messages.INFO,
                             'Grupo modificado exitosamente.')
        return super(GrupoUpdateView, self).form_valid(form)

    def get_initial(self):
        return {'lotes': self.get_object().lotes.all()}

    def get_form_kwargs(self):
        kwargs = super(GrupoUpdateView, self).get_form_kwargs()

        # solo los lotes que no tienen grupo y su subasta no esta cerrada
        lotes = Lote.objects.filter(grupo__subasta__cerrado_el=None,
                                    grupo=None)
        kwargs['lotes'] = lotes | self.get_object().lotes.all()
        return kwargs


class LoteListView(LoginRequiredMixin, ListView):
    model = Lote
    template_name = 'subastas/lotes/list.html'

    def get_queryset(self):
        """Lotes que no tienen grupo (son los de la subasta vigente)"""
        return Lote.objects.filter(grupo__subasta__cerrado_el=None)

subastas_repo/templates/subastas/acreditador.html
{% extends "subastas/bases/acreditador_actero_base.html" %}

{% block content_acreditador_actero %}
    sisi, somos los acreditadores
{% endblock content_acreditador_actero%}

subastas_repo/templates/subastas/acreditador_home.html
{% extends "subastas/bases/acreditador_actero_base.html" %}

{% load crispy_forms_tags %}

{% block content_acreditador_actero %}
    {% if current_subasta %}
        <div class="panel panel-default text-center">

          <div class="panel-heading">
            <h3>
                Subasta N° {{ current_subasta.numero }}
                <span class="small">
                    {{ current_subasta.fecha_hora | date:'d/m/Y' }}
                </span>
            </h3>
            <h4>Inscripciones</h4>
          </div>

          <div class="panel-body">
            <div class="col-md-4">

                <ul class="nav nav-tabs" role="tablist" id="AcreditadoresTab">
                  <li role="presentation" class="{% if tab == 'search' %} active {% endif %}%">
                    <a href="#search" aria-controls="search" role="tab" data-toggle="tab">Buscar inscriptos pasados</a>
                  </li>
                  <li role="presentation" class="{% if tab == 'add' %} active {% endif %}%">
                    <a href="#add" aria-controls="add" role="tab" data-toggle="tab">Inscribir</a>
                  </li>
                </ul>

                <div class="tab-content">
                  <div role="tabpanel" class="tab-pane {% if tab == 'search' %} active {% endif %}" id="search">
                    <h4>{{ form_inscriptions.personas.label }}</h4>

                    <form action="{% url 'subastas:acreditadores' %}">

                      <div class="input-group">
                        <input type="text"
                               class="form-control"
                               placeholder="Buscar por nombre, apellido o dni..."
                               name="q"
                               value="{{ query }}">
                        <span class="input-group-btn">
                          <button type="submit"
                                 class="btn btn-default">
                                 <i class="fa fa-search"></i>
                          </button>
                        </span>
                      </div>
                    </form>

                    <hr style="clear:both;">

                    <form method="POST" action="{% url 'personas:asociar' current_subasta.id %}">{% csrf_token %}

                      <input type="submit" class="btn btn-success btn-lg btn-block" value="Inscribir">

                      <hr style="clear:both;">

                      <ul class="list-group">
                        {% for checkbox in form_inscriptions.personas %}
                            <li class="list-group-item">
                            {{ checkbox.choice_label }}
                            <span class="pull-right">{{ checkbox.tag }} </span>
                            </li>
                        {% endfor %}
                      </ul>
                    </form>
                  </div>

                  <div role="tabpanel" class="tab-pane {% if tab == 'add' %} active {% endif %}%" id="add">
                    {% crispy form form.helper %}
                    <hr>
                  </div>
                </div>
            </div>
            <div class="col-md-8">
                <div class="well well-sm">
                  Personas inscriptas:
                  <span class="badge">{{ personas.count }}</span>
                </div>
                <ul class="list-group">
                    {% for persona in personas %}
                        <li class="list-group-item">
                            {{ persona }}
                            <div class="btn-group pull-right" style="margin: -5px 0px;">
                              <a class="btn btn-sm btn-danger pull-right" href="{% url 'personas:desasociar' current_subasta.id persona.id %}">
                                <i class="fa fa-trash"></i>
                              </a>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
          </div>
        </div>
    {% else %}
        <h2>No hay una subasta en curso.</h2>
    {% endif %}
{% endblock content_acreditador_actero%}

subastas_repo/templates/subastas/actero.html
{% extends "subastas/bases/acreditador_actero_base.html" %}

{% block content_acreditador_actero %}
    hehea los acteros
{% endblock content_acreditador_actero%}

subastas_repo/templates/subastas/actero_home.html
{% extends "subastas/bases/acreditador_actero_base.html" %}

{% block content_acreditador_actero %}
{% endblock content_acreditador_actero%}

subastas_repo/templates/subastas/administrador.html
{% extends 'subastas/bases/admin_base.html' %}

{% block content_administrador %}
    Buenas don admin
{% endblock content_administrador %}

subastas_repo/templates/subastas/administrador_home.html
{% extends 'subastas/bases/admin_base.html' %}

{% block content_administrador %}

    bienvenidor admin {{ user }}

{% endblock content_administrador %}

subastas_repo/templates/subastas/form.html
{% extends 'subastas/bases/admin_base.html' %}

{% load crispy_forms_tags %}

{% block content_administrador %}
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
              <div class="panel-heading clearfix">
                <h1>
                    {% block header %}
                        {% if instance %}
                            Modificar Subasta: {{ instance.fecha_hora|date:'d/m/Y' }}

                            <a href="{% url 'subastas:close' instance.id %}" class="btn btn-sm btn-danger pull-right">
                                Cerrar subasta
                            </a>
                        {% else %}
                            Agregar Subasta
                        {% endif %}

                    {% endblock %}
                </h1>
              </div>
              <div class="panel-body">
                <div>
                    {% crispy form form.helper %}
                </div>
              </div>
            </div>
        </div>
    </div>
{% endblock content_administrador %}

subastas_repo/templates/subastas/list.html
{% extends 'subastas/bases/admin_base.html' %}

{% block content_administrador %}

    <h2>
        Subasta vigente
        {% if not current_subasta %}
            <a class="btn btn-primary pull-right" href="{% url 'subastas:create' %}">Agregar Subasta</a>
        {% endif %}
    </h2>
    {% if current_subasta %}
        <div class="list-group">
            <a href="{% url 'subastas:update' current_subasta.id %}" class="list-group-item list-group-item-success">
                {{ current_subasta.fecha_hora|date:'d/m/Y' }}
                <span class="badge pull-right">
                    Actas: {{ current_subasta.actas.count }}
                </span>
                <span class="badge pull-right">
                    Grupos: {{ current_subasta.grupos.count }}
                </span>
                <span class="badge pull-right">
                    Rodados: {{ current_subasta.bienes.count }}
                </span>
                <span class="badge pull-right">
                    Inscriptos: {{ current_subasta.personas.count }}
                </span>
            </a>
        </div>
    {% else %}
        Ninguna subasta en curso
    {% endif %}

    <h2>Subastas cerradas</h2>
    <div class="list-group">
        {% for subasta in object_list %}
          <a href="#" class="list-group-item">
            {{ subasta.fecha_hora | date:'d/m/Y' }}
            <span class="badge pull-right">
                Actas: {{ subasta.actas.count }}
            </span>
            <span class="badge pull-right">
                Rodados: {{ subasta.bienes.count }}
            </span>
            <span class="badge pull-right">
                Inscriptos: {{ subasta.personas.count }}
            </span>
          </a>
        {% empty %}
            No existen subastas
        {% endfor %}
    </div>


{% endblock content_administrador %}

subastas_repo/templates/subastas/sin_permisos.html
{% extends "base.html" %}

{% block title %}Sin permisos{% endblock %}

{% block content %}
    <h1>Sin permisos</h1>
    <p>
        <h2>
            <a class="btn btn-default" href="{% url 'account_logout' %}">Cerrar sesion e ingresar con otro usuario</a>
        </h2>

    </p>
{% endblock content %}