subastas_repo/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$',  'subastas.views.home', name="home"),

    (r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),

    # User management
    url(r'^users/', include("users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    # Uncomment the next line to enable avatars
    url(r'^avatar/', include('avatar.urls')),

    # Your stuff: custom urls go here
    url(r'^subastas/', include("subastas.urls", namespace="subastas")),
    url(r'^personas/', include("personas.urls", namespace="personas")),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

subastas_repo/users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

from users import views

urlpatterns = patterns('',
    # URL pattern for the UserListView  # noqa
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    # URL pattern for the UserRedirectView
    url(
        regex=r'^redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    # URL pattern of the UserCreateView
    url(
        regex=r'^create$',
        view=views.create_user,
        name='create'
    ),
    # URL patter of the UserUpdateSubastasView
    url(
        regex=r'^update/(?P<user_id>\d+)/$',
        view=views.update_user,
        name='update'
    ),
    url(
        regex=r'^delete/(?P<pk>\d+)/$',
        view=views.UserDeleteView.as_view(),
        name='delete'
    ),
)

subastas_repo/users/models.py
# -*- coding: utf-8 -*-
# Import the AbstractUser model
from django.contrib.auth.models import AbstractUser

# Import the basic Django ORM models library
from django.db import models

from django.utils.translation import ugettext_lazy as _


# Subclass AbstractUser
class User(AbstractUser):

    def __unicode__(self):
        return self.username

subastas_repo/users/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.auth.models import Group
from django.core.urlresolvers import reverse

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Reset, Layout, Div

from .models import User


class UserForm(forms.ModelForm):

    class Meta:
        # Set this form to use the User model.
        model = User

        # Constrain the UserForm to just these fields.
        fields = ("first_name", "last_name")


class CreateUserForm(forms.ModelForm):
    perfil = forms.ModelChoiceField(queryset=Group.objects.all())
    password = forms.CharField(widget=forms.PasswordInput())
    password2 = forms.CharField(label='Repetir password',
                                widget=forms.PasswordInput())

    def __init__(self, *args, **kwargs):
        super(CreateUserForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('user_submit', 'Guardar'))
        self.helper.add_input(Reset('user_reset', 'Limpiar',
                              css_class='btn-default'))

        self.username = None
        if 'instance' in kwargs and kwargs.get('instance') is not None:
            self.username = kwargs['instance'].username

    class Meta:
        # Set this form to use the User model.
        model = User
        fields = ("first_name",
                  "last_name",
                  "username",
                  "password",
                  "password2",
                  "perfil")

    def clean_username(self):
        """Check if the username already exists, and is not his email"""

        username = self.cleaned_data['username']

        if self.username:
            if self.username != username:
                if User.objects.filter(username=username).exists():
                    raise forms.ValidationError("El nombre de usuario ya esta en uso.")
        return username

    def clean(self):
        password = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password2')

        if password and password != password2:
            raise forms.ValidationError("Las contraseñas no son iguales.")

        return self.cleaned_data

subastas_repo/users/views.py
# -*- coding: utf-8 -*-

from django.contrib.auth.decorators import login_required

# Import the reverse lookup function
from django.core.urlresolvers import reverse
from django.core.urlresolvers import reverse_lazy

from django.shortcuts import render, redirect

# view imports
from django.views.generic import DetailView
from django.views.generic import DeleteView
from django.views.generic import RedirectView
from django.views.generic import UpdateView
from django.views.generic import ListView

from allauth.account.models import EmailAddress
# Only authenticated users can access views using this.
from braces.views import LoginRequiredMixin

# Import the form from users/forms.py
from .forms import CreateUserForm, UserForm

# Import the customized User model
from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    form_class = UserForm

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"

    def get_queryset(self):
        return User.objects \
            .exclude(id=self.request.user.id) \
            .exclude(is_superuser=True)


@login_required
def create_user(request):
    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.groups.add(form.cleaned_data.get('perfil'))
            user.set_password(form.cleaned_data.get('password'))
            user.save()
            EmailAddress.objects.create(user=user,
                                        email=user.username,
                                        verified=True)
            return redirect(reverse("users:list"))
    else:
        form = CreateUserForm()
    return render(request, 'users/user_form.html',
                  {'form': form})


def update_user(request, user_id):
    instance = User.objects.get(id=user_id)
    if request.method == "POST":
        form = CreateUserForm(request.POST, instance=instance)
        if form.is_valid():
            user = form.save()
            user.groups.clear()
            user.groups.add(form.cleaned_data.get('perfil'))
            user.set_password(form.cleaned_data.get('password'))
            user.save()
            EmailAddress.objects.get_or_create(user=user,
                                               email=user.username,
                                               verified=True)
            return redirect(reverse("users:list"))
    else:
        form = CreateUserForm(instance=instance,
                              initial={'perfil': instance.groups.last()})
    return render(request, 'users/user_form.html',
                  {'form': form,
                   'instance': instance})


class UserDeleteView(LoginRequiredMixin, DeleteView):
    model = User
    success_url = reverse_lazy('users:list')

subastas_repo/templates/users/user_confirm_delete.html
{% extends 'subastas/bases/admin_base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block content_administrador %}
    <div class="row">
        <div class="col-md-12">
            <h4>
                {% block header %}
                    <p>Seguro que deseas eliminar a "{{ object }}"?</p>
                {% endblock %}
            </h4>
            <form action="{% url 'users:delete' object.id %}" method="post">{% csrf_token %}
                <input type="submit" value="Eliminar" class="btn btn-danger"/>
            </form>

        </div>
    </div>
{% endblock content_administrador %}

subastas_repo/templates/users/user_detail.html
{% extends "base.html" %}
{% load avatar_tags %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->     
<div class="row">

  <div class="col-sm-12 ">
    <a class="btn btn-primary" href="{% url 'users:update' %}">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}">E-Mail</a>
    <a class="btn btn-info" href="{% url 'avatar_change' %}">Avatar</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

subastas_repo/templates/users/user_form.html
{% extends 'subastas/bases/admin_base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block content_administrador %}
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h1>
                    {% block header %}
                        {% if instance %}
                            Modificar usuario: {{ instance }}
                        {% else %}
                            Agregar Usuario
                        {% endif %}
                    {% endblock %}
                </h1>
              </div>
              <div class="panel-body">
                <form method="POST"
                      class="form-horizontal"
                      action="{% if instance %}
                                {% url 'users:update' instance.id %}
                              {% else %}
                                {% url 'users:create' %}
                              {% endif %}">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="control-group">
                      <div class="controls">
                        <button type="submit" class="btn btn-success">Aplicar</button>
                        {% if instance %}
                            <a href="{% url 'users:delete' instance.id %}" class="btn btn-danger">
                                Eliminar
                            </a>
                        {% endif %}
                      </div>
                    </div>
                </form>
              </div>
            </div>

        </div>
    </div>
{% endblock content_administrador %}

subastas_repo/templates/users/user_list.html
{% extends 'subastas/bases/admin_base.html' %}

{% load static %}{% load i18n %}

{% block content_administrador %}

    <div class="row">
      <div class="col-md-12">
        <h2>
          Usuarios

          <a class="btn btn-primary pull-right" href="{% url 'users:create' %}">Agregar usuario</a>
        </h2>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <div class="list-group">
            {% for user in user_list %}
              <a href="{% url 'users:update' user.id %}" class="list-group-item">
                {{ user.username }}
                {% for group in user.groups.all %}
                  <span class="label label-default pull-right">
                    {{ group.name }}
                  </span>
                {% endfor %}
              </a>
            {% endfor %}
        </div>
      </div>
    </div>

{% endblock content_administrador %}