subastas_repo/subastas/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

from . import views

urlpatterns = patterns('subastas.views',
    url(
        regex=r'^$',
        view=views.SubastaListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^nuevo/$',
        view=views.SubastaCreateView.as_view(),
        name='create'
    ),
    url(
        regex=r'^editar/(?P<pk>\d+)/$',
        view=views.SubastaUpdateView.as_view(),
        name='update'
    ),
    url(
        regex=r'^cerrar/(?P<subasta_id>\d+)/$',
        view=views.cerrar_subasta,
        name='close'
    ),
    url(
        regex=r'^actas/$',
        view=views.ActaListView.as_view(),
        name='actas'
    ),
    url(
        regex=r'^actas/nuevo/$',
        view=views.ActaCreateView.as_view(),
        name='actas_create'
    ),
    url(
        regex=r'^imprimir/(?P<pk>\d+)/$',
        view=views.ActaPrintView.as_view(),
        name='print'
    ),
    url(
        regex=r'^acreditadores/$',
        view=views.AcreditadorHomeView.as_view(),
        name='acreditadores'
    ),
    url(
        regex=r'^bienes/$',
        view=views.RodadoListView.as_view(),
        name='rodados'
    ),
    url(
        regex=r'^bienes/nuevo/$',
        view=views.RodadoCreateView.as_view(),
        name='rodados_create'
    ),
    url(
        regex=r'^bienes/editar/(?P<pk>\d+)/$',
        view=views.RodadoUpdateView.as_view(),
        name='rodados_update'
    ),
    url(
        regex=r'^bienes/nuevo/xlsx/$',
        view=views.upload_xlsx,
        name='rodados_nuevo_xlsx'
    ),
    url(
        regex=r'^grupos/$',
        view=views.GrupoListView.as_view(),
        name='grupos'
    ),
    url(
        regex=r'^grupos/(?P<pk>\d+)$',
        view=views.GrupoDetailView.as_view(),
        name='grupos_detail'
    ),
    url(
        regex=r'^grupos/nuevo/$',
        view=views.GrupoCreateView.as_view(),
        name='grupos_create'
    ),
    url(
        regex=r'^grupos/editar/(?P<pk>\d+)/$',
        view=views.GrupoUpdateView.as_view(),
        name='grupos_update',
    ),
    url(
        regex=r'^lotes/$',
        view=views.LoteListView.as_view(),
        name='lotes'
    ),
    url(
        regex=r'^lotes/(?P<pk>\d+)/$',
        view=views.LoteDetailView.as_view(),
        name='lotes_detail'
    ),
    url(
        regex=r'^lotes/nuevo/$',
        view=views.LoteCreateView.as_view(),
        name='lotes_create'
    ),
    url(
        regex=r'^lotes/editar/(?P<pk>\d+)/$',
        view=views.LoteUpdateView.as_view(),
        name='lotes_update'
    ),
    # Sin permisos
    url(
        regex=r'^sin_permisos/$',
        view=TemplateView.as_view(
            template_name='subastas/sin_permisos.html'),
        name='sin_permisos'
    ),
)

subastas_repo/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$',  'subastas.views.home', name="home"),

    (r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),

    # User management
    url(r'^users/', include("users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    # Uncomment the next line to enable avatars
    url(r'^avatar/', include('avatar.urls')),

    # Your stuff: custom urls go here
    url(r'^subastas/', include("subastas.urls", namespace="subastas")),
    url(r'^personas/', include("personas.urls", namespace="personas")),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

subastas_repo/subastas/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse, reverse_lazy
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.views.generic import CreateView
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic import UpdateView
from django.views.generic import FormView

from braces.views import LoginRequiredMixin

from personas.forms import PersonaForm
from personas.models import Persona
from .forms import (ActaForm,
                    GrupoForm,
                    InscriptionForm,
                    LoteForm,
                    RodadoForm,
                    SubastaForm)
from .models import (Acta,
                     Grupo,
                     Lote,
                     Rodado,
                     Subasta)


@login_required
def home(request):
    if request.user.groups.filter(name="administradores").exists():
        url = 'subastas:list'
    elif request.user.groups.filter(name="acreditadores").exists():
        url = 'subastas:acreditadores'
    elif request.user.groups.filter(name="acteros").exists():
        url = 'subastas:actas'
    else:
        url = 'subastas:sin_permisos'

    return redirect(reverse(url))


class SubastaListView(LoginRequiredMixin, ListView):
    model = Subasta
    template_name = 'subastas/list.html'

    def get_queryset(self):
        """Subastas anteriores o cerradas"""
        return Subasta.objects.filter(Q(cerrado_el__lte=timezone.now()) |
                                      Q(fecha_hora__lte=timezone.now()))


class SubastaCreateView(LoginRequiredMixin, CreateView):
    form_class = SubastaForm
    model = Subasta
    success_url = reverse_lazy('subastas:list')
    template_name = 'subastas/form.html'

    def form_valid(self, form):
        form.save()
        messages.add_message(self.request,
                             messages.INFO,
                             'Subasta creada exitosamente.')
        return super(SubastaCreateView, self).form_valid(form)


class SubastaUpdateView(LoginRequiredMixin, UpdateView):
    context_object_name = 'instance'
    form_class = SubastaForm
    model = Subasta
    success_url = reverse_lazy('subastas:list')
    template_name = 'subastas/form.html'

    def form_valid(self, form):
        messages.add_message(self.request,
                             messages.INFO,
                             'Subasta modificada exitosamente.')
        return super(SubastaUpdateView, self).form_valid(form)


def cerrar_subasta(request, subasta_id):
    subasta = get_object_or_404(Subasta, pk=subasta_id)
    subasta.cerrado_el = timezone.now()
    subasta.save()
    messages.add_message(request,
                         messages.INFO,
                         'Subasta cerrada exitosamente.')
    return redirect(reverse_lazy("subastas:list"))


class ActaListView(LoginRequiredMixin, ListView):
    model = Acta
    template_name = 'subastas/actas/list.html'

    def get_queryset(self):
        self.current_subasta = Subasta.objects.get_current()
        if self.current_subasta:
            return self.current_subasta.actas.all()
        else:
            return None


class ActaCreateView(LoginRequiredMixin, CreateView):
    form_class = ActaForm
    model = Acta
    template_name = 'subastas/actas/form.html'
    success_url = reverse_lazy('subastas:actas')

    def form_valid(self, form):
        acta_nueva = form.save(commit=False)
        acta_nueva.subasta = Subasta.objects.get_current()
        acta_nueva.save()
        messages.add_message(self.request,
                             messages.INFO,
                             'Acta agregada exitosamente.')
        return super(ActaCreateView, self).form_valid(form)


class ActaPrintView(LoginRequiredMixin, DetailView):
    model = Acta
    template_name = 'subastas/actas/print.html'

    def get_context_data(self, **kwargs):
        context = super(ActaPrintView, self).get_context_data(**kwargs)
        acta = kwargs.get('object')
        context['bienes'] = Rodado.objects.filter(lote=acta.lote)
        return context


class AcreditadorHomeView(LoginRequiredMixin, FormView):
    form_class = PersonaForm
    model = Persona
    success_url = reverse_lazy('subastas:acreditadores')
    template_name = 'subastas/acreditador_home.html'

    def get_context_data(self, **kwargs):
        self.current_subasta = Subasta.objects.get_current()
        context = super(AcreditadorHomeView, self).get_context_data(**kwargs)
        if self.current_subasta:
            context['personas'] = self.current_subasta.personas.all() \
                .order_by('apellidos')

            query = self.request.GET.get('q', '')
            context['form_inscriptions'] = InscriptionForm(
                instance=self.current_subasta, query=query)

            context['tab'] = self.request.GET.get('tab', 'search')
            context['query'] = query
        return context

    def form_valid(self, form):
        self.current_subasta = Subasta.objects.get_current()
        persona_acreditada = form.save()
        self.current_subasta.personas.add(persona_acreditada)
        messages.add_message(self.request,
                             messages.INFO,
                             'Inscripcion exitosa.')
        return redirect(reverse_lazy("subastas:acreditadores"))

    def form_invalid(self, form):
        return super(AcreditadorHomeView, self).form_invalid(form)


class RodadoListView(LoginRequiredMixin, ListView):
    model = Rodado
    template_name = 'subastas/rodados/list.html'

    def get_queryset(self):
        """Bienes sin subastar"""
        return Rodado.objects.no_subastados()


class RodadoCreateView(LoginRequiredMixin, CreateView):
    form_class = RodadoForm
    model = Rodado
    template_name = 'subastas/rodados/form.html'
    success_url = reverse_lazy('subastas:rodados')

    def form_valid(self, form):
        messages.add_message(self.request,
                             messages.INFO,
                             'Bien cargado exitosamente.')
        return super(RodadoCreateView, self).form_valid(form)


class RodadoUpdateView(LoginRequiredMixin, UpdateView):
    context_object_name = 'instance'
    form_class = RodadoForm
    model = Rodado
    success_url = reverse_lazy('subastas:rodados')
    template_name = 'subastas/rodados/form.html'

    def form_valid(self, form):
        messages.add_message(self.request,
                             messages.INFO,
                             'Bien modificado exitosamente.')
        return super(RodadoUpdateView, self).form_valid(form)


def upload_xlsx(request):
    if request.method == "POST":
        rodados_cargados = Rodado.objects \
            .load_bienes(request.FILES['bienes_file'])
        messages.add_message(request,
                             messages.INFO,
                             'Bienes cargados: %s' % (rodados_cargados))
    return render(request, 'subastas/rodados/cargar_xlsx.html')


class GrupoListView(LoginRequiredMixin, ListView):
    model = Grupo
    template_name = 'subastas/grupos/list.html'

    def get_queryset(self):
        """Grupos de la subasta vigente"""
        subasta = Subasta.objects.get_current()
        return subasta.grupos.all()


class GrupoDetailView(LoginRequiredMixin, DetailView):
    model = Grupo
    template_name = 'subastas/grupos/detail.html'


class GrupoCreateView(LoginRequiredMixin, CreateView):
    form_class = GrupoForm
    model = Grupo
    template_name = 'subastas/grupos/form.html'
    success_url = reverse_lazy('subastas:grupos')

    def form_valid(self, form):
        grupo = form.save(commit=False)
        grupo.subasta = Subasta.objects.get_current()
        grupo.save()

        lotes = form.cleaned_data.get('lotes', None)
        if lotes:
            lotes.update(grupo=grupo)
        messages.add_message(self.request,
                             messages.INFO,
                             'Grupo cargado exitosamente.')
        return super(GrupoCreateView, self).form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(GrupoCreateView, self).get_form_kwargs()

        # solo los lotes que no tienen grupo y su subasta no esta cerrada
        lotes = Lote.objects.filter(grupo__subasta__cerrado_el=None,
                                    grupo=None)
        kwargs['lotes'] = lotes
        return kwargs


class GrupoUpdateView(LoginRequiredMixin, UpdateView):
    context_object_name = 'instance'
    form_class = GrupoForm
    model = Grupo
    success_url = reverse_lazy('subastas:grupos')
    template_name = 'subastas/grupos/form.html'

    def form_valid(self, form):
        grupo = form.save(commit=False)
        grupo.lotes.update(grupo=None)

        lotes = form.cleaned_data.get('lotes', None)
        if lotes:
            lotes.update(grupo=grupo)

        messages.add_message(self.request,
                             messages.INFO,
                             'Grupo modificado exitosamente.')
        return super(GrupoUpdateView, self).form_valid(form)

    def get_initial(self):
        return {'lotes': self.get_object().lotes.all()}

    def get_form_kwargs(self):
        kwargs = super(GrupoUpdateView, self).get_form_kwargs()

        # solo los lotes que no tienen grupo y su subasta no esta cerrada
        lotes = Lote.objects.filter(grupo__subasta__cerrado_el=None,
                                    grupo=None)
        kwargs['lotes'] = lotes | self.get_object().lotes.all()
        return kwargs


class LoteListView(LoginRequiredMixin, ListView):
    model = Lote
    template_name = 'subastas/lotes/list.html'

    def get_queryset(self):
        """Lotes que no tienen grupo (son los de la subasta vigente)"""
        return Lote.objects.filter(grupo__subasta__cerrado_el=None)

subastas_repo/templates/subastas/actas/form.html
{% extends "subastas/bases/acreditador_actero_base.html" %}

{% load crispy_forms_tags %}

{% block content_acreditador_actero %}

    {% crispy form form.helper %}

{% endblock content_acreditador_actero%}

subastas_repo/templates/subastas/actas/list.html
{% extends "subastas/bases/acreditador_actero_base.html" %}

{% block content_acreditador_actero %}

    {% if current_subasta %}
      <div class="panel panel-default text-center">

        <div class="panel-heading">
          <h3>
              Subasta N° {{ current_subasta.numero }}
              <span class="small">
                  {{ current_subasta.fecha_hora | date:'d/m/Y' }}
              </span>
          </h3>
          <h4>Actas</h4>
        </div>

        <div class="panel-body">
          <div class="col-md-12">
            <h2>
              &nbsp;
              <a class="btn btn-primary pull-right" href="{% url 'subastas:actas_create' %}">Agregar Acta</a>
            </h2>

            <div class="list-group">
              {% for acta in object_list %}
                <a href="{% url 'subastas:print' acta.id %}" class="list-group-item">
                  {{ acta }}
                </a>
              {% empty %}
                  No hay actas.
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    {% else %}
      <h2>No hay una subasta en curso.</h2>
    {% endif %}
{% endblock content_acreditador_actero%}

subastas_repo/templates/subastas/actas/print.html
{% load date_to_words %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Acta</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="text-center">ACTA DE SUBASTA</h1>
                <h2 class="text-center">
                    LOTE N° {{ object.bien_rodado.lote }}
                </h2>
                <p>
                    ----En la ciudad de RESISTENCIA - CHACO, a los {{ object.subasta.fecha_hora|dia_literal }} ({{ object.subasta.fecha_hora|date:'d' }}) dias del mes de {{ object.subasta.fecha_hora|mes_literal }} de {{ object.subasta.fecha_hora|date:'Y' }}, en {{ object.subasta.domicilio.descripcion }} sito en {{ object.subasta.domicilio.direccion }}, siendo las {{ object.subasta.fecha_hora|hora_literal }} horas se da comienzo el acto de la subasta, por Cuenta y Orden del GOBIERNO DE LA PROVINCIA DEL CHACO, por Decreto N° {{ object.subasta.decreto }}, del Poder Ejecutivo, a través de la Subsecretaria de Coordinación y Gestión Pública, a cargo de la Cra. Maris Telma Gamón, y cuyo edicto fuera publicado por cinco (5) días en Boletin Oficial, diario local, diarios provinciales y nacionales. Tomando participación para este acto el Martillero Publico {{ object.lote.grupo.martillero }} (Matricula N° {{ object.lote.grupo.martillero.matricula }}), con el Grupo N° {{ object.lote.grupo.numero }}, da comienzo con los automotores: LOTE N° {% if object.lote.chatarra %} de chatarra {% endif %} {% if bienes.count > 1 %} compuesto por {% for bien in bienes %}
                        un (1) {{ bien.descripcion }} {{ bien.marca }}
                    {% endfor %}
                    {% else %} {% endif %}
                </p>
            </div>
        </div>
    </div>
</body>
</html>


<ul>
    <li>id: {{ object.id }}</li>
    <li>bien rodado: {{ bienes }}</li>
    <li>quien lo compro?: {{ object.persona }}</li>
    <li>profesionales:
        <ul>
            {% for profesional in object.profesionales.all %}
                <li>{{ profesional }}</li>
            {% endfor %}
        </ul>
    </li>
    <li>descripcion: {{ object.descripcion }}</li>
</ul>