subastas_repo/personas/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url

from personas import views

urlpatterns = patterns('',
    url(
        regex=r'^asociar/(?P<subasta_id>\d+)$',
        view=views.asociar,
        name='asociar'
    ),
    url(
        regex=r'^desasociar/(?P<subasta_id>\d+)/(?P<persona_id>\d+)$',
        view=views.desasociar,
        name='desasociar'
    ),
    url(
        regex=r'^profesionales/$',
        view=views.ProfesionalListView.as_view(),
        name='profesionales_list'
    ),
    url(
        regex=r'^profesionales/create/$',
        view=views.ProfesionalCreateView.as_view(),
        name='profesionales_create'
    ),
    url(
        regex=r'^profesionales/update/(?P<pk>\d+)/$',
        view=views.ProfesionalUpdateView.as_view(),
        name='profesionales_update'
    ),
    url(
        regex=r'^profesionales/delete/(?P<pk>\d+)/$',
        view=views.ProfesionalDeleteView.as_view(),
        name='profesionales_delete'
    ),
)

subastas_repo/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$',  'subastas.views.home', name="home"),

    (r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),

    # User management
    url(r'^users/', include("users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    # Uncomment the next line to enable avatars
    url(r'^avatar/', include('avatar.urls')),

    # Your stuff: custom urls go here
    url(r'^subastas/', include("subastas.urls", namespace="subastas")),
    url(r'^personas/', include("personas.urls", namespace="personas")),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

subastas_repo/personas/models.py
# -*- coding: utf-8 -*-

from django.db import models

from model_utils import Choices


class Persona(models.Model):
    nombres = models.CharField(max_length=100, blank=True, null=True)
    apellidos = models.CharField(max_length=100, blank=True, null=True)
    razon_social = models.CharField(max_length=100, blank=True, null=True)

    dni = models.CharField(max_length=10, blank=True, null=True, unique=True)
    cuit = models.CharField(max_length=15, blank=True, null=True)

    domicilio = models.ForeignKey("Domicilio")
    telefono = models.CharField(max_length=20)

    def __unicode__(self):
        return "%s, %s (%s)" % (self.apellidos, self.nombres, self.dni)


class Titulo(models.Model):
    nombre = models.CharField(max_length=100)

    def __unicode__(self):
        return self.nombre


class Profesional(models.Model):
    nombres = models.CharField(max_length=100)
    apellidos = models.CharField(max_length=100)
    dni = models.CharField('DNI',
                           max_length=10,
                           blank=True,
                           null=True)
    titulo = models.ForeignKey(Titulo, blank=True, null=True)
    matricula = models.CharField('Número Matrícula',
                                 max_length=50,
                                 blank=True,
                                 null=True)
    telefono = models.CharField('Teléfono',
                                max_length=20,
                                blank=True,
                                null=True)

    def __unicode__(self):
        return "%s, %s" % (self.apellidos, self.nombres)

    class Meta:
        verbose_name_plural = 'Profesionales'


class Domicilio(models.Model):
    direccion = models.CharField(max_length=80)
    descripcion = models.TextField(blank=True, null=True)
    localidad = models.ForeignKey('Localidad')

    def __unicode__(self):
        return self.direccion


class Localidad(models.Model):
    nombre = models.CharField(max_length=50)
    codigo_postal = models.CharField(max_length=15)

    def __unicode__(self):
        return "%s (%s)" % (self.nombre, self.codigo_postal)

    class Meta:
        verbose_name_plural = 'Localidades'

subastas_repo/personas/forms.py
from django import forms
from django.core.urlresolvers import reverse

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Reset, Layout, Div

from .models import Persona, Profesional


class ProfesionalForm(forms.ModelForm):
    class Meta:
        fields = ["nombres",
                  "apellidos",
                  "dni",
                  "titulo",
                  "matricula",
                  "telefono"]
        model = Profesional


class PersonaForm(forms.ModelForm):
    nombres = forms.CharField()
    apellidos = forms.CharField()
    razon_social = forms.CharField()
    dni = forms.CharField()
    cuit = forms.CharField()

    class Meta:
        model = Persona
        fields = ['nombres',
                  'apellidos',
                  'razon_social',
                  'dni',
                  'cuit',
                  'domicilio',
                  'telefono']

    def __init__(self, *args, **kwargs):
        super(PersonaForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_method = 'POST'
        self.helper.form_action = reverse('subastas:acreditadores')
        self.helper.add_input(Submit('user_submit', 'Guardar'))
        self.helper.add_input(Reset('user_reset', 'Limpiar',
                              css_class='btn-default'))
        self.helper.layout = Layout(
            Div('nombres',
                'apellidos',
                'razon_social',
                'dni',
                'cuit',
                'domicilio',
                'telefono')
        )

subastas_repo/personas/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from django.views.generic import CreateView
from django.views.generic import DeleteView
from django.views.generic import ListView
from django.views.generic import UpdateView
from django.shortcuts import get_object_or_404, render, redirect

from braces.views import LoginRequiredMixin

from personas.forms import ProfesionalForm
from subastas.forms import InscriptionForm
from subastas.models import Subasta
from .models import Persona, Profesional


@login_required
def asociar(request, subasta_id):
    subasta = get_object_or_404(Subasta, pk=subasta_id)
    if request.method == "POST":
        form = InscriptionForm(request.POST, instance=subasta)
        if form.is_valid():
            personas = form.cleaned_data.get('personas')
            subasta.personas.add(*personas)
            msg = 'Usuarios agregados exitosamente.'
        else:
            msg = 'No tiene personas tildadas.'
        messages.add_message(request,
                             messages.INFO,
                             msg)
    return redirect(reverse_lazy('subastas:acreditadores')+'?tab=search')


@login_required
def desasociar(request, subasta_id, persona_id):
    subasta = get_object_or_404(Subasta, pk=subasta_id)
    persona = get_object_or_404(Persona, pk=persona_id)
    subasta.personas.remove(persona)
    messages.add_message(request,
                         messages.INFO,
                         'Se borro la inscripcion exitosamente.')
    return redirect(reverse_lazy('subastas:acreditadores')+'?tab=search')


class ProfesionalListView(LoginRequiredMixin, ListView):
    model = Profesional
    template_name = 'personas/profesionales/list.html'

    def get_queryset(self):
        return Profesional.objects.all().order_by('titulo')


class ProfesionalCreateView(LoginRequiredMixin, CreateView):
    form_class = ProfesionalForm
    model = Profesional
    template_name = 'personas/profesionales/form.html'
    success_url = reverse_lazy('personas:profesionales_list')


class ProfesionalUpdateView(LoginRequiredMixin, UpdateView):
    context_object_name = 'instance'
    form_class = ProfesionalForm
    model = Profesional
    template_name = 'personas/profesionales/form.html'
    success_url = reverse_lazy('personas:profesionales_list')


class ProfesionalDeleteView(LoginRequiredMixin, DeleteView):
    model = Profesional
    template_name = 'personas/profesionales/confirm_delete.html'
    success_url = reverse_lazy('personas:profesionales_list')

subastas_repo/templates/personas/profesionales/confirm_delete.html
{% extends 'subastas/bases/admin_base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block content_administrador %}
    <div class="row">
        <div class="col-md-12">
            <h4>
                {% block header %}
                    <p>Seguro que deseas eliminar a "{{ object }}"?</p>
                {% endblock %}
            </h4>
            <form action="{% url 'personas:profesionales_delete' object.id %}" method="post">{% csrf_token %}
                <input type="submit" value="Eliminar" class="btn btn-danger"/>
            </form>

        </div>
    </div>
{% endblock content_administrador %}

subastas_repo/templates/personas/profesionales/form.html
{% extends 'subastas/bases/admin_base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block content_administrador %}
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h1>
                    {% block header %}
                        {% if instance %}
                            Modificar profesional: {{ instance }}
                        {% else %}
                            Agregar Profesional
                        {% endif %}
                    {% endblock %}
                </h1>
              </div>
              <div class="panel-body">
                <div>
                    <form method="POST"
                          class="form-horizontal"
                          action="{% if instance %}
                                    {% url 'personas:profesionales_update' instance.id %}
                                  {% else %}
                                    {% url 'personas:profesionales_create' %}
                                  {% endif %}">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <div class="control-group">
                          <div class="controls">
                            <button type="submit" class="btn btn-success">Aplicar</button>
                            {% if object %}
                                <a href="{% url 'personas:profesionales_delete' object.id %}" class="btn btn-danger">
                                    Eliminar
                                </a>
                            {% endif %}
                          </div>
                        </div>
                    </form>
                </div>
              </div>
            </div>
        </div>
    </div>
{% endblock content_administrador %}

subastas_repo/templates/personas/profesionales/list.html
{% extends 'subastas/bases/admin_base.html' %}

{% load static %}{% load i18n %}

{% block content_administrador %}

    <div class="row">
      <div class="col-md-12">
        <h2>
          Profesionales

          <a class="btn btn-primary pull-right" href="{% url 'personas:profesionales_create' %}">Agregar profesional</a>
        </h2>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <div class="list-group">
            {% for profesional in profesional_list %}
              <a href="{% url 'personas:profesionales_update' profesional.id %}" class="list-group-item">
                {{ profesional }}
                <span class="label label-default pull-right">
                  {{ profesional.titulo }}
                </span>
              </a>
            {% endfor %}
        </div>
      </div>
    </div>

{% endblock content_administrador %}